name: Deploy React + Vite to GitHub Pages

on:
    workflow_dispatch:
    push:
        branches:
            - main


jobs:
    build-deploy:
        runs-on: ubuntu-latest
        
        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup Nodejs
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            # Install dependencies (client)
            - name: Install dependencies
              working-directory: ./client
              run: npm ci

            # Build the project
            - name: Build project (Vite with GitHub Pages base)
              working-directory: ./client
              env:
                VITE_DEPLOY: github
                VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
              run: npm run build

            # Add SPA fallback (serve index.html on 404 refreshes)
            - name: Add 404.html fallback
              working-directory: ./client/dist
              run: cp index.html 404.html
            
            # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: client/dist



            